feat: add validation for SignUp and Login modal
BeerCodeIndustry/qideo pull request #23
Opened 2022-10-18 19:32 UTC by VladPlakhotnik

It remains only to add a POEditor

2022-10-18 19:43 UTC, neverwanalive commented
мда ну и хуита

2022-10-18 19:44 UTC, VladPlakhotnik commented
?

2022-10-19 09:40 UTC, ordinaryask requested changes

2022-10-19 09:40 UTC, ordinaryask commented on src/components/SignUp/SignUp.component.tsx
> +        <FormContainer flexDirection='column'>
u can use simple Flexbox

2022-10-19 09:40 UTC, ordinaryask commented on src/components/Login/Login.component.tsx
> +        <FormContainer flexDirection='column'>
u can use simple Flexbox

2022-10-19 09:48 UTC, ordinaryask approved these changes

2022-10-19 09:48 UTC, merged